# https://taskfile.dev

version: "2"

tasks:
  default:
    cmds:
      - mkdir -p out
      - rm -f out/*
      - go build -o out/main src/main.go
      - ./out/main
    silent: false
  gen-config:
    cmds:
      - echo "export DOTA_PATH=replace_me" > env.local.sh
  set-env:
    cmds:
      - source env.local.sh
  copy-replays:
    deps:
      - set-env
    cmds:
      - mkdir -p replays
      - rm -f replays/*
      - cp -r "{{.DOTA_PATH}}"/replays .
      - rm replays/placeholder.txt
